### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by gforcada** [collective/haufe.requestmonitoring#12]
I see that on `master` there are already the changes to support py3 and zope4, but there is no release with those changes, are there other known issues that prevent such a release to happen? :slightly_smiling_face:

**Comment by gforcada** [comment]
@zopyx @jensens @keul as you three seem to be the pypi maintainers of this package, could you have some time to create a new release? I could cut it myself if given permissions on pypi 👍🏾

**Comment by zopyx** [comment]
@gforcada I added "gforcada" as owner on PyPI

**Comment by gforcada** [comment]
Thanks :)

**Comment by gforcada** [comment]
@zopyx sorry, now that I notice, my userid on pypi is `gilforcada` rather than `gforcada` 😓 sorry I did not notice until I was about to make a release

**Comment by zopyx** [comment]
> @zopyx sorry, now that I notice, my userid on pypi is `gilforcada` rather than `gforcada` 😓 sorry I did not notice until I was about to make a release

Done

**Comment by gforcada** [comment]
🎉 version 0.6.0 is out! please give it a try and report issues about it :)

**Comment by gforcada** [comment]
@zopyx thanks!!
